# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19MjzVazGLe9WcZQe1tEXQf0qwz0oijei
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os


# ============================================================
# CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Car Price Prediction",
    page_icon="🚗",
    layout="wide"
)


# ============================================================
# CHARGEMENT DU MODÈLE ET DES ENCODEURS
# ============================================================

@st.cache_resource
def load_model():
    model = joblib.load("best_model.joblib")
    encoders = joblib.load("encoders.joblib")

    # Les encodeurs ont été sauvegardés sous forme de liste
    if isinstance(encoders, list):
        cat_cols = [
            "Fuel_Type",
            "Seller_Type",
            "Transmission"
        ]

        encoders = dict(zip(cat_cols, encoders))

    return model, encoders


try:
    model, encoders = load_model()

except Exception as e:
    st.error("Erreur lors du chargement du modèle ou des encodeurs.")
    st.exception(e)
    st.stop()


# ============================================================
# TITRE
# ============================================================

st.title("🚗 Prédiction du prix de vente d'une voiture")
st.write(
    "Cette application utilise un modèle de Machine Learning "
    "pour prédire le prix de vente d'une voiture d'occasion."
)


# ============================================================
# FONCTION DE PRÉDICTION
# ============================================================

def predict_price(
    kms_driven,
    present_price,
    fuel_type,
    seller_type,
    transmission,
    age
):

    # Encodage des variables catégorielles
    fuel_enc = encoders["Fuel_Type"].transform([fuel_type])[0]

    seller_enc = encoders["Seller_Type"].transform([seller_type])[0]

    transmission_enc = encoders["Transmission"].transform(
        [transmission]
    )[0]

    # Même ordre que lors de l'entraînement
    x_new = np.array([[
        kms_driven,
        present_price,
        fuel_enc,
        seller_enc,
        transmission_enc,
        age
    ]], dtype=float)

    # Prédiction
    prediction = model.predict(x_new)[0]

    return float(prediction)


# ============================================================
# ONGLETS
# ============================================================

tab1, tab2 = st.tabs([
    "🔮 Prédiction simple",
    "📂 Prédiction multiple"
])


# ============================================================
# PRÉDICTION SIMPLE
# ============================================================

with tab1:

    st.subheader("Informations sur la voiture")

    col1, col2 = st.columns(2)

    with col1:

        kms_driven = st.number_input(
            "Kilométrage (Kms_Driven)",
            min_value=0.0,
            value=50000.0,
            step=1000.0
        )

        present_price = st.number_input(
            "Prix catalogue neuf (Present_Price)",
            min_value=0.0,
            value=5.0,
            step=0.1
        )

        age = st.number_input(
            "Âge du véhicule (années)",
            min_value=0,
            max_value=50,
            value=5,
            step=1
        )

    with col2:

        fuel_type = st.selectbox(
            "Type de carburant",
            options=list(encoders["Fuel_Type"].classes_)
        )

        seller_type = st.selectbox(
            "Type de vendeur",
            options=list(encoders["Seller_Type"].classes_)
        )

        transmission = st.selectbox(
            "Transmission",
            options=list(encoders["Transmission"].classes_)
        )

    st.divider()

    if st.button(
        "🚀 Prédire le prix",
        type="primary",
        use_container_width=True
    ):

        try:

            prediction = predict_price(
                kms_driven,
                present_price,
                fuel_type,
                seller_type,
                transmission,
                age
            )

            st.success("Prédiction réalisée avec succès !")

            st.metric(
                label="Prix de vente prédit",
                value=f"{prediction:.2f} k$"
            )

        except Exception as e:

            st.error("Une erreur est survenue pendant la prédiction.")
            st.exception(e)


# ============================================================
# PRÉDICTION MULTIPLE PAR CSV
# ============================================================

with tab2:

    st.subheader("Prédiction à partir d'un fichier CSV")

    st.write(
        "Votre fichier CSV doit contenir les colonnes suivantes :"
    )

    st.code(
        "Kms_Driven, Present_Price, Fuel_Type, "
        "Seller_Type, Transmission, Age"
    )

    uploaded_file = st.file_uploader(
        "Importer votre fichier CSV",
        type=["csv"]
    )

    if uploaded_file is not None:

        try:

            df_input = pd.read_csv(uploaded_file)

            st.write("### Aperçu des données")

            st.dataframe(
                df_input.head(),
                use_container_width=True
            )

            required_columns = [
                "Kms_Driven",
                "Present_Price",
                "Fuel_Type",
                "Seller_Type",
                "Transmission",
                "Age"
            ]

            missing_columns = [
                col for col in required_columns
                if col not in df_input.columns
            ]

            if missing_columns:

                st.error(
                    "Colonnes manquantes : "
                    + ", ".join(missing_columns)
                )

            else:

                if st.button(
                    "🚀 Prédire les prix",
                    type="primary"
                ):

                    predictions = []

                    for _, row in df_input.iterrows():

                        prediction = predict_price(
                            row["Kms_Driven"],
                            row["Present_Price"],
                            row["Fuel_Type"],
                            row["Seller_Type"],
                            row["Transmission"],
                            row["Age"]
                        )

                        predictions.append(prediction)

                    # Ajouter les prédictions
                    df_result = df_input.copy()

                    df_result["Predicted_Selling_Price"] = predictions

                    st.success(
                        "Les prédictions ont été générées avec succès !"
                    )

                    st.write("### Résultats")

                    st.dataframe(
                        df_result,
                        use_container_width=True
                    )

                    # Conversion en CSV
                    csv = df_result.to_csv(
                        index=False
                    ).encode("utf-8")

                    st.download_button(
                        label="⬇️ Télécharger les prédictions",
                        data=csv,
                        file_name="predictions.csv",
                        mime="text/csv"
                    )

        except Exception as e:

            st.error(
                "Impossible de traiter le fichier CSV."
            )

            st.exception(e)


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.header("ℹ️ À propos")

    st.write(
        "Application de prédiction du prix de vente "
        "des voitures d'occasion."
    )

    st.write("### Variables utilisées")

    st.write(
        """
        - Kms_Driven
        - Present_Price
        - Fuel_Type
        - Seller_Type
        - Transmission
        - Age
        """
    )

    st.write("### Modèle")

    st.write(
        "Le modèle sélectionné lors de l'entraînement "
        "est chargé depuis `best_model.joblib`."
    )